// <auto-generated />
namespace ContosoUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonAjaxJSONModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonAjaxJSONModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201605041515221_PersonAjaxJSON Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
